// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1PbHCSt49LYBsrpKONx23KSoVlK9JPA',
    appId: '1:902289788373:web:bae982ee9d57f39c17415c',
    messagingSenderId: '902289788373',
    projectId: 'gdsc-e798f',
    authDomain: 'gdsc-e798f.firebaseapp.com',
    storageBucket: 'gdsc-e798f.appspot.com',
    measurementId: 'G-7X63VD2GC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUv4ZBk2rXJKIHUMJ7LSqCpL3J4gv4BlU',
    appId: '1:902289788373:android:f5f429537032a80417415c',
    messagingSenderId: '902289788373',
    projectId: 'gdsc-e798f',
    storageBucket: 'gdsc-e798f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSdp0TT9vdH3Ul59sBO_OgPA_xoI3Kd_A',
    appId: '1:902289788373:ios:b96e0ef482c4759617415c',
    messagingSenderId: '902289788373',
    projectId: 'gdsc-e798f',
    storageBucket: 'gdsc-e798f.appspot.com',
    androidClientId: '902289788373-ajcktv3ph2dv0ec76bu1utj8h79om4en.apps.googleusercontent.com',
    iosClientId: '902289788373-7ct82nv5mb2manjdnbqerjn7cfvmn82v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscComoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSdp0TT9vdH3Ul59sBO_OgPA_xoI3Kd_A',
    appId: '1:902289788373:ios:b96e0ef482c4759617415c',
    messagingSenderId: '902289788373',
    projectId: 'gdsc-e798f',
    storageBucket: 'gdsc-e798f.appspot.com',
    androidClientId: '902289788373-ajcktv3ph2dv0ec76bu1utj8h79om4en.apps.googleusercontent.com',
    iosClientId: '902289788373-7ct82nv5mb2manjdnbqerjn7cfvmn82v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscComoda',
  );
}
